language: generic
script:
 - |
       curl -s \
       -X POST \
       -d chat_id=$TEST_MESSAGE_ID \
       -d text="${TRAVIS_COMMIT_MESSAGE}" \
       https://api.telegram.org/bot$TB_TOKEN/sendMessage
branches:
  only:
    - feature/refactoring-folders
